# Generated by Django 4.2.1 on 2023-09-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo_author',
        ),
        migrations.AddField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to='book_photos'),
        ),
    ]
