# Generated by Django 4.2.1 on 2023-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
